'use server';
import fs from 'fs';
import path from 'path';
import csv from 'csv-parser';

// import { createClient } from '@/utils/supabase/server'
// import { cookies } from 'next/headers'
//
// export async function getVendors() {
//     const cookiesStore = await cookies();
//     const supabase = createClient(cookiesStore);
//     const { data: vendors } = await supabase
//         .from('vendors')
//         .select('*');
//     return vendors;
// }
export async function getVendors() {
  const results = [
    {
      'Record ID': '0a17b3fb-932d-4f16-b5bd-1737531a2f6d',
      Record: 'Startup CPG',
      Categories: 'Community & Network',
      'Location > State': 'NY',
      Website: 'https://startupcpg.com/',
      contact: 'Daniel Scharff, Peter Boyajian',
      emailContact: 'peter@peterboyajian.com',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America',
      clients: '',
    },
    {
      'Record ID': '0a7afdd8-67d2-4946-a265-077827df714a',
      Record: 'Grande Cheese Company',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'WI',
      Website: 'https://grande.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location:
        '250 Camelot Drive Fond du Lac, WI 54935, WI, United States of America',
      clients: '',
    },
    {
      'Record ID': '0d55feb3-7026-4e94-b326-6c20abb4e205',
      Record: 'My Cooking Box',
      Categories: 'PR & Marketing',
      'Location > State': 'NY',
      Website: 'https://mycookingbox.it/',
      contact: 'Chiara Rota',
      emailContact: 'info@mycookingbox.it',
      about: '',
      services: '',
      phone: '354236154',
      location: 'New York City, NY, United States of America',
      clients: '',
    },
    {
      'Record ID': '18fed4dc-08d2-46c4-b011-67cf2c701c5f',
      Record: 'UNFI (4 Yearly Shows)',
      Categories: 'Event & Trade show',
      'Location > State': 'NY',
      Website: 'https://www.unfi.com/news-and-resources/events.html',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '1fb317c8-a8e8-427b-88ab-6689eeac539c',
      Record: 'Assembled Brands',
      Categories: 'Financing & Working Capital',
      'Location > State': 'CA',
      Website: 'https://www.assembledbrands.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Los Angeles, CA, United States of America ',
      clients: '',
    },
    {
      'Record ID': '27410949-9a47-4b24-936d-2dcaadd9b6dc',
      Record: 'Opply',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'IL',
      Website: 'https://opply.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Chicago, IL, United States of America ',
      clients: '',
    },
    {
      'Record ID': '2ca036d1-7dce-40b8-9e00-28301caba5e6',
      Record: 'Palermo Villa',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'WI',
      Website: 'https://www.palermovillainc.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location:
        '3301 W Canal St Milwaukee, WI 53208, WI, United States of America ',
      clients: '',
    },
    {
      'Record ID': '2e488f8d-32fa-4055-850b-b1b41d3cdb0f',
      Record: 'Morrison Seger Venture',
      Categories: 'Investor',
      'Location > State': 'TX',
      Website: 'https://www.morrisonseger.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Dallas, TX, United States of America ',
      clients: '',
    },
    {
      'Record ID': '2eb5bc1b-4882-49bc-9bb0-da5aec526431',
      Record: "Coal'd Water Distilling Company",
      Categories: 'Co-Packer & Co-Manufacturer',
      'Location > State': 'TN',
      Website: 'coaldwater.com',
      contact: '',
      emailContact: '',
      about:
        "Coal'd Water Distilling Company can help manufacturers meet production demands with our newly-installed canning line capable of running standard and sleek cans from 8oz sleek to 19.2oz standard. With a natural-spring on-site, we have the freshest water for still/sparkling, and can adapt the line to run carbonated beverages, cold brew coffees, RTD cocktails, THC-infused beverages, and others. We are located in East Tennessee at the foothills of the Great Smoky Mountains. ",
      services:
        'Our canning capabilities include sleek and standard cans from 8oz to 19.2oz. Loose cans or cartons into shrink-wrapped trays. We can handle still/sparkling waters, cold brew coffees, RTD cocktails, THC-infused beverages, carbonated beverages and energy drinks. The current line runs up to 100 cans per minute, and we will be functional at 200 cans per minute in 2026. ',
      phone: '8655097007',
      location:
        '3169 Old Highway 411. Dandridge, TN 37725, TN, United States of America ',
      clients: '',
    },
    {
      'Record ID': '31c22981-5b8c-4b32-8ded-d70a6857187b',
      Record: 'Jaguar Freight',
      Categories: 'Logistics & Warehouse',
      'Location > State': 'NY',
      Website: 'https://jaguarfreight.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '4495445e-c114-4a7e-9e4d-4d15252bcd33',
      Record: 'Bertozzi',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'CT',
      Website: 'https://www.bertozziamerica.com',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Norwalk, CT, United States of America ',
      clients: '',
    },
    {
      'Record ID': '466e4aea-a056-4f9c-9e8b-94c97a8da30e',
      Record: 'Giannuzzi Lewendon',
      Categories: 'Legal services',
      'Location > State': 'NY',
      Website: 'https://gllaw.us/',
      contact: 'Anthony Iuzzolino, Ryn Hall ',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '4f29a075-c340-4692-beca-ea90296075e0',
      Record: 'Gander Agency',
      Categories: 'Branding & Packaging',
      'Location > State': 'NY',
      Website: 'https://takeagander.com/',
      contact: '',
      emailContact: 'hello@takeagander.com',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '6ca14fda-c3e7-42ce-b350-df08b36cf387',
      Record: 'Ferraro Foods',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'NJ',
      Website: 'https://www.ferrarofoods.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location:
        '287 South Randolphville Rd Piscataway, NJ 08854, NJ, United States of America ',
      clients: '',
    },
    {
      'Record ID': '6de16896-a93c-45dc-8232-34dff6ee52ca',
      Record: 'Summer Fancy Food Show',
      Categories: 'Event & Trade show',
      'Location > State': 'NY',
      Website: 'https://www.specialtyfood.com/fancy-food-shows/summer/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '7784a1e8-205f-4952-be74-9301139cf2a1',
      Record: 'SIGEP',
      Categories: 'Event & Trade show',
      'Location > State': '',
      Website: 'https://www.sigep.it',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: '',
      clients: '',
    },
    {
      'Record ID': '7cb3e195-de53-4d7b-99a0-a2c183f01364',
      Record: 'Newtopia Now',
      Categories: 'Event & Trade show',
      'Location > State': 'CO',
      Website: 'https://www.newtopianow.com/en/home.html',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Denver, CO, United States of America ',
      clients: '',
    },
    {
      'Record ID': '81de697d-14b4-4278-9ed3-63f09b3b3237',
      Record: 'UNFI (Level Up)',
      Categories: 'Accelerator & Incubator',
      'Location > State': 'NY',
      Website: 'https://www.unfi.com/services/supplier-services/up-next.html',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '8bd633a7-15e8-4a0f-bd06-94e27dfe5aea',
      Record: 'Naturally Network',
      Categories: 'Community & Network',
      'Location > State': 'TX',
      Website: 'https://www.naturallynetwork.org/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Austin, TX, United States of America ',
      clients: '',
    },
    {
      'Record ID': '9a55f862-861e-4931-a33f-a881958935f7',
      Record: 'Sansone Foods',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'NY',
      Website: 'https://www.sansonefoods.com/',
      contact: '',
      emailContact: 'info@sansonefoods.com',
      about: '',
      services: '',
      phone: '',
      location:
        '2133 Jericho Turnpike Garden City Park, NY 11040, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': '9c788744-adf2-4f3f-a028-925f9e902b2e',
      Record: 'National Co+op Grocers',
      Categories: 'Event & Trade show',
      'Location > State': 'MN',
      Website: 'https://www.ncg.coop/convergence-exhibitor-information',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Saint Paul, MN, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'a557a8c8-f0b9-444e-b745-5f5fd4943052',
      Record: 'Tarter Krinsky & Drogin',
      Categories: 'Legal services',
      'Location > State': 'NY',
      Website: 'https://www.tarterkrinsky.com/',
      contact: 'Maurizio Anglani',
      emailContact: 'manglani@tarterkrinsky.com',
      about: '',
      services: '',
      phone: '',
      location: 'New York, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'aaa4097d-5e44-4b89-bbd2-9fa7457e1980',
      Record: 'Buck Agency',
      Categories: 'Branding & Packaging',
      'Location > State': 'NY',
      Website: 'https://buck.co/',
      contact: '',
      emailContact: 'newbiz.ny@buck.co',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'ab80cdf7-4c2f-4fd1-8db8-3cdcb1c69774',
      Record: 'The Angel Group',
      Categories: 'Investor',
      'Location > State': 'NY',
      Website: 'https://www.wearetheangelgroup.com/',
      contact: '',
      emailContact: 'hello@wearetheangelgroup.com',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'ace8962e-87b4-425e-baac-f3e037dbbf85',
      Record: 'Pizza Group',
      Categories: 'Equipment & Facility',
      'Location > State': 'TX',
      Website: 'https://www.pizzagroup.com/en/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Houston, TX, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'b24970e9-217e-4f4d-9653-11004135db54',
      Record: 'UNFI',
      Categories: 'Retailer & Distributor',
      'Location > State': 'RI',
      Website: 'https://www.unfi.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Providence, RI, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'b9269341-090b-4ce5-84c1-e2f5fcbab853',
      Record: 'Funaro & Co.',
      Categories: 'Accounting & Tax',
      'Location > State': 'NY',
      Website: 'https://www.funaro.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'd246ecba-3aaf-4572-bae7-13a98372e881',
      Record: 'KeHe (Yearly Shows)',
      Categories: 'Event & Trade show',
      'Location > State': 'IL',
      Website: 'https://www.kehe.com/events/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Chicago, IL, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'e40f9435-1933-4a3c-a8fa-9a6280213907',
      Record: 'Winter Fancy Food Show',
      Categories: 'Event & Trade show',
      'Location > State': 'CA',
      Website: 'https://www.specialtyfood.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'San Diego, CA, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'e73e524a-42cf-428e-b68c-874bd562dd60',
      Record: 'Whole Foods (LEAP)',
      Categories: 'Accelerator & Incubator',
      'Location > State': 'TX',
      Website:
        'https://www.preparedfoods.com/articles/130201-applications-open-for-whole-foods-market-2025-local-and-emerging-accelerator-program',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Austin, TX, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'ed33ac3f-3ca1-4906-b2fc-08f83465ecd8',
      Record: 'Independent Hunter',
      Categories: 'Sales & Broker',
      'Location > State': 'NY',
      Website: 'https://www.independenthunter.com',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'New York City, NY, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'efa20673-fd90-4804-b29c-471f511839c5',
      Record: 'Stanislaus',
      Categories: 'Flavors & Ingredients',
      'Location > State': 'CA',
      Website: 'https://stanislaus.com/',
      contact: 'Tom Cortopassi',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location:
        '1202 D Street, Modesto, CA 95354, CA, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'f09447e9-0e72-4a71-92a8-371136e20432',
      Record: 'Green Spoon',
      Categories: 'Sales & Broker',
      'Location > State': 'CO',
      Website: 'https://www.greenspoonsales.com/',
      contact: '',
      emailContact: 'info@greenspoonsales.com',
      about: '',
      services: '',
      phone: '',
      location: 'Boulder, CO, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'f276b647-b3fc-4ef3-89d6-5609ab9b4a22',
      Record: 'Buttermilk Creative',
      Categories: 'Branding & Packaging',
      'Location > State': 'FL',
      Website: 'https://www.buttermilk.com/',
      contact: '',
      emailContact: 'https://www.buttermilk.com/',
      about: '',
      services: '',
      phone: '',
      location: 'Miami, FL, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'f37e5d5b-ba55-4911-99dc-e090db49437f',
      Record: 'Expo West',
      Categories: 'Event & Trade show',
      'Location > State': 'CA',
      Website: 'https://www.expowest.com/en/home.html',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'Anaheim, CA, United States of America ',
      clients: '',
    },
    {
      'Record ID': 'ff6e40b4-ffbd-4d12-93c2-0c55b00144d9',
      Record: 'VMG Partners',
      Categories: 'Investor',
      'Location > State': 'CA',
      Website: 'https://www.vmgpartners.com/',
      contact: '',
      emailContact: '',
      about: '',
      services: '',
      phone: '',
      location: 'San Francisco, CA, United States of America ',
      clients: '',
    },
  ];

  return results.map((vendor) => ({
    id: vendor['Record ID'] || '',
    name: vendor['Record'] || '',
    state: vendor['Location > State'] || '',
    website: vendor['Website'] || '',
    categories: vendor['Categories'] || '',
    ...vendor,
  }));
}

export async function getVendor(id) {
  const vendors = await getVendors();
  return vendors.find((vendor) => vendor.id === id);
}

export async function getDataForVendorDetails(id) {
  const vendors = await getVendors();
  const totalVendors = vendors.length;
  const vendorIndex = vendors.findIndex((vendor) => vendor.id === id);
  const previousVendor =
    vendors[(vendorIndex - 1 + totalVendors) % totalVendors];
  const nextVendor = vendors[(vendorIndex + 1) % totalVendors];
  const vendor = vendors.find((vendor) => vendor.id === id);
  return { vendor, previousVendor, nextVendor, vendorIndex, totalVendors };
}
